import OpenAI from 'openai';
import vm from 'vm';
import dotenv from 'dotenv';
import logger from '../services/logger.js';
import { withRetry } from './llmUtils.js';

dotenv.config();

const openai = new OpenAI({
  apiKey: process.env.OPENROUTER_API_KEY,
  baseURL: 'https://openrouter.ai/api/v1',
});

const MATH_PROMPT = `
You are a Senior Data Scientist and Javascript Developer.
Your task is to generate a PURE JAVASCRIPT snippet that performs mathematical calculations on a provided 'data' object.

DATA STRUCTURE:
The 'data' object has this structure:
{
  "columns": ["Account", "Jan", "Feb", ...],
  "rows": [
    { "Account": "Income", "Jan": 100, "Feb": 120 },
    { "Account": "Expense", "Jan": 50, "Feb": 60 }
  ]
}

YOUR TASK:
1. Generate Javascript code that mutates the 'data' object directly.
2. Typically, you will add a new row to 'data.rows' or a new column to 'data.columns' (and update all rows).
3. Handle missing values as 0.
4. **FINANCIAL LOGIC RULES**:
   - For Income/Revenue accounts: Variance = (Current - Previous).
   - For **Expense** and **Cost of Sales (COS)** accounts: Variance = (Previous - Current).
     *Logic: An increase in expense is a negative variance for financial performance.*
   - When calculating "Variance" or "Variance %", always check the account name/key to apply the correct sign.
5. Return ONLY raw Javascript code. No markdown, no backticks, no explanation.

EXAMPLE:
User: "Calculate Profit as Income - Expense"
Output:
const profitRow = { Account: "Profit" };
data.columns.forEach(col => {
  if (col !== "Account") {
    const inc = data.rows.find(r => r.Account === "Income")?.[col] || 0;
    const exp = data.rows.find(r => r.Account === "Expense")?.[col] || 0;
    profitRow[col] = inc - exp;
  }
});
data.rows.push(profitRow);
`;

export class MathAgent {
  async applyMath(data: any, instructions: string, modelId: string): Promise<any> {
    try {
      logger.info('MathAgent: Generating calculation code...', { instructions });

      const response = await withRetry(() => openai.chat.completions.create({
        model: modelId,
        messages: [
          { role: 'system', content: MATH_PROMPT },
          { role: 'user', content: `Instructions: ${instructions}\n\nCurrent Data Sample: ${JSON.stringify({
            columns: data.columns,
            rows: data.rows.slice(0, 5) // Send a sample to help the LLM understand the keys
          })}` }
        ],
        temperature: 0,
      }));

      const code = response.choices[0]?.message?.content?.replace(/```javascript/g, '').replace(/```/g, '').trim();
      
      if (!code) {
        logger.warn('MathAgent: No code generated by LLM.');
        return data;
      }

      logger.info('MathAgent: Executing generated code...', { code });

      // Create a secure sandbox
      const sandbox = { data: JSON.parse(JSON.stringify(data)) };
      vm.createContext(sandbox);
      
      try {
        vm.runInContext(code, sandbox, { timeout: 2000 });
        return sandbox.data;
      } catch (execError: any) {
        logger.error('MathAgent: Code execution failed', { error: execError.message, code });
        return data; // Fallback to original data
      }
    } catch (error: any) {
      logger.error('MathAgent: Failed to process math', { error: error.message });
      return data;
    }
  }
}

export const mathAgent = new MathAgent();
